### PR TITLE
float button discovering the next and previous diff

### PR DESCRIPTION
**Pull request by PhoebeWho**
As with the issue https://github.com/rtfpessoa/diff2html/issues/189 for a button discovering the next and previous diff, I have realized the function in my web. Please check if you'd like to add this function.

### CODE REVIEW

**Comment by PhoebeWho** [comment]
I'm sorry all checks are failed. It may because I wrote **style="position: fixed;left: 100px;"** inside the mustache file...

**Comment by rtfpessoa** [comment]
@PhoebeWho thanks for your contribution.

I have some concerns with this implementation:
* The floating buttons appear over the diffs (e.g. the line numbers)
* Seems like it only works for the first two elements
* I think you should be able to to it all without changing anything except the diff2html-ui

Can you check my comments?

Ideally you can rely on the siblings of the dom to navigate.

**Comment by rtfpessoa** [comment]
Closing for inactivity. Let me know if you want to look at this in the future.

**Comment by PAX523** [comment]
@rtfpessoa I cannot see your comments in his changes. What tasks are outstanding?

**Comment by rtfpessoa** [comment]
Is just above the last message: https://github.com/rtfpessoa/diff2html/pull/210#pullrequestreview-232529135

**Pull request closed without merging**
