### PR TITLE
[ON_HOLD] use lodash merge cherry picked

### PR DESCRIPTION
**Pull request by YOU54F**
UPDATE
_________

Under investigation, see dkelosky/jest-stare#81 (comment)

ORIGINAL
__________
Hi @rtfpessoa,

It looks like the change to `merge` has broken depedants `jest-stare`

Using v2.9.0 of `diff2html`, fails 2 snapshots which are using the diff2html

see failing build 
https://travis-ci.com/dkelosky/jest-stare/builds/111186557
and PR raised against jest-stare
https://github.com/dkelosky/jest-stare/pull/81

Using my fork with lodash cherry picked

https://github.com/YOU54F/jest-stare/pull/3
https://github.com/YOU54F/diff2html/pull/1
https://travis-ci.org/YOU54F/jest-stare/builds/530266195

Not sure if the dist folder should be updated as part of PR?

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@YOU54F that is quite strange.
Are you sure the update broke that? Weren't you using an older version and other update in the middle changed that?

I would really like to not bring all of lodash as a dependency. Can you investigate a bit more to see if it was really the last version? Merge should do the same result.

**Comment by YOU54F** [comment]
Certainly my friend, it is peculiar. The test failures were consistently showing the same difference in 2 snapshot tests when consuming v2.0.7 to v2.0.9 of this repo.

I don’t maintain jest-state but was just chasing some vulnerabilities in our dep chain, so am not too familiar with the code base so will dig a little deeper and let you know!

**Comment by rtfpessoa** [comment]
I did some testing and commented here https://github.com/dkelosky/jest-stare/pull/81#issuecomment-491414520. Will hold this PR until we decide on the results.

**Comment by YOU54F** [comment]
Thank you @rtfpessoa, I am happy to close this for now and will re-open if it is relevant, otherwise I can just mark the title as on hold?

**Comment by rtfpessoa** [comment]
Closing for now. Will re-open if needed.

**Pull request closed without merging**
