### PR TITLE
release: New major refactor of diff2html to Typescript

### PR DESCRIPTION
**Pull request by rtfpessoa**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Hi @FredrikNoren and @pbu88,
Since you are probably the biggest users of diff2html I would love for you to test the pre-versions for 3.x that I have been releasing.
Now I do not have any more plans to perform changes and I have not found any more bugs.

If you could try to upgrade to `3.0.0-master.df4481f` by following the updated documentation in the README and give me some feedback, it would be hugely appreciated.
If you need any help let me know.

I would love to release when I get your feedback.

**Comment by FredrikNoren** [comment]
@campersau

**Comment by campersau** [comment]
I have updated ungit to the latest diff2html release [here](https://github.com/FredrikNoren/ungit/compare/master...campersau:update_diff2html) and it seems to work as before 👍 .
The only thing I have noticed is that the `drawFileList` option defaults to `true` instead of `false` as stated in the [README.md](https://github.com/rtfpessoa/diff2html/blob/master/README.md#diff2html-configuration).
https://github.com/rtfpessoa/diff2html/blob/f1ff703e644894ae6826a4dec31c31442b57c5c4/src/diff2html.ts#L21

**Comment by rtfpessoa** [comment]
Thanks for testing it @campersau, sorry about the mistake I just pushed a commit in this PR fixing the default in the README.

Maybe I will eventually work on something that can generate that from the code.

**Comment by rtfpessoa** [comment]
Tag release

**Pull request merged**
