### PR TITLE
Fix regex to strip timestamp when timezone is behind GMT

### PR DESCRIPTION
**Pull request by romellem**
The regex used to strip out the `diff` timestamps does not work when the timezone is behind GMT. 

This PR fixes the regex, and adds another test to ensure the timestamps are correctly stripped.

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Thanks for the PR @romellem do you know what happens if we are on GMT?

Maybe we should allow `[-+]{0,1}\d{4}` also?

**Comment by pbu88** [comment]
Good catch! I think this should be fine, UTC timezone offset is normally represented by +0000:

    $ date -uR
    Mon, 09 Oct 2017 16:08:57 +0000

**Comment by romellem** [comment]
Manually setting the timezone on my computer to GMT yields a timestamp like so:

    2017-10-04 22:12:40.000000000 +0000

So I think we are good in assuming it will always have a plus or minus.

However, briefly going through [diffutil's source code](http://savannah.gnu.org/git/?group=diffutils) to try and figure out how they format the timestamps, in their CHANGELOG they have:

> ```
> User-visible changes in version 2.8:
> * diff uses ISO 8601 style timestamps for output times (e.g. "2001-11-23
>   16:44:36.875702460 -0800") unless in the C or POSIX locale and the
>   -c style is specified.
>```

I also see in **diffutil.texi**:

>```
> @vindex LC_TIME
>@cindex timestamp format, context diffs
>The timestamp normally looks like @samp{2002-02-21 23:30:39.942229878
>-0800} to indicate the date, time with fractional seconds, and time
>zone in @uref{ftp://ftp.isi.edu/in-notes/rfc2822.txt, Internet RFC
>2822 format}.  (The fractional seconds are omitted on hosts that do
>not support fractional timestamps.)  However, a traditional timestamp
>like @samp{Thu Feb 21 23:30:39 2002} is used if the
>@env{LC_TIME} locale category is either @samp{C} or @samp{POSIX}.
>```

So I guess technically the timestamp could be completely different.

Up to you all if you want a more robust regex to catch `C` or `POSIX` locales.

**Comment by romellem** [comment]
Better format for the documentation: https://www.gnu.org/software/diffutils/manual/diffutils.html#Detailed-Context

**Comment by romellem** [comment]
Also found the relevant C code for their formatting ('./src/diff.c', Line 680):

```C
  if (output_style != OUTPUT_CONTEXT || hard_locale (LC_TIME))
    {
#if (defined STAT_TIMESPEC || defined STAT_TIMESPEC_NS \
     || defined HAVE_STRUCT_STAT_ST_SPARE1)
      time_format = "%Y-%m-%d %H:%M:%S.%N %z";
#else
      time_format = "%Y-%m-%d %H:%M:%S %z";
#endif
    }
  else
    {
      /* See POSIX 1003.1-2001 for this format.  */
      time_format = "%a %b %e %T %Y";
    }
```

**Comment by rtfpessoa** [comment]
@romellem would you be up to adding the remaining formats or should I merge this and create a issue for it?

**Comment by romellem** [comment]
Yeah, I'd be down to try and add support for the `POSIX 1003.1-2001` format.

However, just for organization, I think it makes sense to merge this in, and open a new issue. When I get home I'll check it out and submit a new PR.

**Comment by rtfpessoa** [comment]
Sounds good to me.

**Comment by rtfpessoa** [comment]
Created https://github.com/rtfpessoa/diff2html/issues/144

**Pull request merged**
