### PR TITLE
Use nunjucks templates

### PR DESCRIPTION
**Pull request by rtfpessoa**
Based on the work done by @pbu88 in #51 this PR fixes the browser version.

By reading this [https://github.com/mozilla/nunjucks/issues/507#issuecomment-137976028](https://github.com/mozilla/nunjucks/issues/507#issuecomment-137976028) and this [https://github.com/mozilla/nunjucks/blob/master/bin/bundle.js](https://github.com/mozilla/nunjucks/blob/master/bin/bundle.js) I was able to make a less agressive solution.

**NOTE:** Works npm 3.7.0, lower versions might not work due to the new `node_modules` directory format.

**TIP:** `npm install npm@3.7.0 -g`

### CODE REVIEW

**Comment by pbu88** [comment]
Too bad that we need so many workarounds for making this work :(
Why do we need to pre-compile? My main concern is that it might be too hard to extend and use custom templates. I know I need this feature really bad because I want to customise the templates for Diffy, so I was thinking to extend them. Maybe is possible, I'll see what I run into when I try it.

Other than that I think is good, maybe it'll get simpler with future development.

**Comment by rtfpessoa** [comment]
The last version doesn't look so bad.

The pre-compilation is advised for production. If you do not use it I think it might get slow or something like that.

Still we are only using the pre-compiled version in the browser.

**Comment by pbu88** [comment]
True, let's see how it works so we can keep moving forward. I'll start working on the SideBySide :)

**Comment by pbu88** [comment]
Hey @rtfpessoa, do you need me to do something else about this? Let me know how can I help you (with this or something else :) )

**Comment by rtfpessoa** [comment]
@pbu88 sorry about the delay I need to merge this, will do it as soon as I can.

**Comment by pbu88** [comment]
Sure, it's a big change. We'll need to test how well it works from diff2html-cli. Let me know if you need a hand. Thanks!

**Comment by rtfpessoa** [comment]
@pbu88 after some more testing, I found one problem:

* When the line content exceed the screen size, it goes to the next line and gets mixed, this is not happening without nunjucks. Any ideas if an HTML class changed or something that can cause this?

**Comment by rtfpessoa** [comment]
@pbu88 I think I found it. When you removed the `white-space: pre;` it got the lines breaking randomly when they were big. By adding `white-space: nowrap;` it is fixed.

**Comment by pbu88** [comment]
Oh, cool! Good catch! Now that the css changed, I wonder if we have to update diff2html-cli.

**Comment by rtfpessoa** [comment]
Already started using the css from this project, so it should not need any manual changes regarding the css.

**Comment by pbu88** [comment]
Hey @rtfpessoa thanks for the hard work testing this stuff. It wasn't easy, specially with all the webpack issues that appeared. Quick question, do we need to track the "dist" files with git? Because they get change every time we run `release.sh`.

Oh, nice about using the css from the project, let me see how you did that :) I was afraid that the removal of `pre` CSS would break CLI.

**Comment by rtfpessoa** [comment]
Regarding the `dist` folder, it also bothers me to commit it, but the `dist` folder has the contents for bower and webjars.

If you have any good ideas on how to avoid this let me know.

About the cli I did a dirty hack. Using the root directory I find diff2html inside the node_modules folder and grab the css contents and paste them in the html. This allows for the html to be portable.

**Pull request merged**
