### PR TITLE
Fix bug in change grouping algorithm

### PR DESCRIPTION
**Pull request by escitalopram**
This fixes the problem mentioned at the end of pull request #34

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@escitalopram thanks for the quick fix. Looks amazing. Great work :+1:

**Comment by rtfpessoa** [comment]
released as version 1.2.0

**Comment by rtfpessoa** [comment]
@escitalopram line matching is now default on the sample here: http://rtfpessoa.xyz/diff2html/

**Comment by escitalopram** [comment]
@rtfpessoa I think it would be more intuitive to demo it with a line-by-line diff, how about you?

**Comment by rtfpessoa** [comment]
@escitalopram I have both, if you scroll you have the other. I need to add some design to that page to make it more pleasant to navigate and see different options.

**Comment by escitalopram** [comment]
@rtfpessoa  What I wanted to point out is, that the *matching* is active for the line-by-line diff and not for the side-by-side diff. If you want do demo diff2html with and without matching, I think enabling it for the side-by-side example would be more intuitive

    // generate and inject the diff HTML into the desired place
    document.getElementById("line-by-line").innerHTML = Diff2Html.getPrettyHtml(diffJson, { inputFormat: 'json', showFiles: true, matching: 'lines' });
    document.getElementById("side-by-side").innerHTML = Diff2Html.getPrettyHtml(diffJson, { inputFormat: 'json', outputFormat: 'side-by-side' });

**Comment by rtfpessoa** [comment]
@escitalopram, ops missed it. Just updated. Thanks.

**Pull request merged**
