### PR TITLE
add ignore white spaces to side by side view

### PR DESCRIPTION
**Pull request by moehawamdeh**
This is to add the functionality of ignoring white spaces, I added only to side by side view for demonstration purpose, the concept is to skip a line that has repeated space and both before and after changes takes place in same line.

To pass the all the unit tests I added reverted a commit that skips some context line when white spaces are ignored, as it makes the overall document more relevant (c1d670169950c2f8d71a8f691f7314263e2cc3b9). but I really think it makes sense to skip these context lines.

### CODE REVIEW

**Comment by rtfpessoa** [comment]
👋 This is something that is usually available at the diff level (e.g.: git diff provides it OOTB) so I would think this is not something we should add to the tool.

Can you let me know what is the use case here?

**Comment by moehawamdeh** [comment]
> wave Sorry for the delay. This is something that is usually available at the diff level (e.g.: git diff provides it OOTB) so I would think this is not something we should add to the tool.
> 
> Can you let me know what is the use case here?

Sometimes you have no full control on generating the diff output, for example at my use case am getting it from Gitlab Api which doesn't have the option to commit whitespace, one can argue that its more reasonable to have Gitlab adding that to API, but I think its also a good option to have here at the plugin, what do you think?

**Comment by rtfpessoa** [comment]
To accept this I will need both styles to support it. Side by side and line by line. And also to have some tests and see how it behaves in corner cases.
Can you start by showing some examples of how you would like it to behave?

**Comment by rtfpessoa** [comment]
Closed due to inactivity

**Pull request closed without merging**
