### PR TITLE
Remove timestamps from filenames in unified diffs

### PR DESCRIPTION
**Pull request by pbu88**
On diffy.org several people have uploaded unified diffs and the timestamps were showing on the filenames. Apparently the parsers doesn't strip them out of the headers. I looked at the tests and all of the unified diffs there were without timestamps but according to the GNU site they will always be there when using the `diff` command (https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html).

This is how the unified diff looks like when using `diff2html-cli` (look at the filename):

image

What this PR does is just an extra step to see if there's a timestamp in the filename and strip it off.

### CODE REVIEW

**Comment by rtfpessoa** [comment]
I started doing this but I guess I left it in the middle.

In here https://github.com/pbu88/diff2html/blob/a481fad7caa3dd489fafdb141517c3d39090f568/src/diff-parser.js#L252 I already have the format.

I think it would make more sense to make this fix either in the get filename methods or do it in a regex like the other fields. What do you think?

**Comment by pbu88** [comment]
I see, I thought about including it in the Regex, we could do that. Right now it's inside _getFilename method so not sure what you mean by "make this fix either in the get filename methods".

If you prefer I can include it in the regex, maybe makes more sense although I'm not sure if it will complicate things in the case an actual filename is named with a timestamp :)

**Comment by rtfpessoa** [comment]
Sorry for the delay. I misread the diff. It looks nice.

Thanks for the fix.

**Comment by rtfpessoa** [comment]
Released as version `diff2html@2.0.10`

**Comment by pbu88** [comment]
Oh cool! Thanks.

**Pull request merged**
