### PR TITLE
Add Robusta to list of projects using diff2html

### PR DESCRIPTION
**Pull request by aantn**
This adds https://github.com/robusta-dev/robusta to the list of projects using diff2html.

We use diff2html and love it :)

### CODE REVIEW

**Comment by aantn** [comment]
Do I need to do anything to get the validate-and-publish workflow to pass?

**Comment by rtfpessoa** [comment]
> Do I need to do anything to get the validate-and-publish workflow to pass?

No it is just missing the credentials. I need to update that as there are solutions already.

LGTM 👍

**Comment by aantn** [comment]
Thank you, we're honored to be listed on the website :)

**Comment by rtfpessoa** [comment]
Great that diff2html is being useful to you.

**Comment by rtfpessoa** [comment]
Completely forgot to approve the release of the website. Now it already appear there.

**Pull request merged**
